version: '3'

volumes:
  mysql_database_personas:

services:

  mysql_database_personas:
    image: mysql:8.0.34
    volumes:
      - mysql_database_personas:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  eureka-server:
    image: agvi_eureka_server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  gateway:
    image: agvi_gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
      - personas
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    ports:
      - "8080:8080"
    links:
      - eureka-server

  personas:
    image: agvi_personas
    build: ./Persona
    restart: always
    ports:
      - "9091:8081"
    depends_on:
      - mysql_database_personas
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_personas:3306/personas?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server
