version: '3'

volumes:
  mysql_database_personas:
  mysql_database_destinos:
  mysql_database_vueloreserva:
  mysql_database_alojamientos:
  keycloak_data:

services:

  mysql_database_personas:
    image: mysql:8.0.34
    volumes:
      - mysql_database_personas:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_destinos:
    image: mysql:8.0.34
    volumes:
      - mysql_database_destinos:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234
  mysql_database_vueloreserva:
    image: mysql:8.0.34
    volumes:
      - mysql_database_vueloreserva:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234
  mysql_database_alojamientos:
    image: mysql:8.0.34
    volumes:
      - mysql_database_alojamientos:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234


  eureka-server:
    image: agvi_eureka_server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  gateway:
    image: agvi_gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
      - personas
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:9090/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:9090/realms/tutorial-api/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    links:
      - eureka-server

  personas:
    image: agvi_personas
    build: ./Persona
    restart: always
    ports:
      - "9091:8081"
    depends_on:
      - mysql_database_personas
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_personas:3306/personas?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq
    links:
      - eureka-server

  destinos:
    image: agvi_destinos
    build: ./destino
    restart: always
    depends_on:
      - mysql_database_destinos
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_destinos:3306/destinos?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  vueloreserva:
    image: agvi_vueloreserva
    build: ./VueloReserva
    restart: always
    depends_on:
      - mysql_database_vueloreserva
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_vueloreserva:3306/vueloreserva?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq
    links:
      - eureka-server

  alojamientos:
    image: agvi_alojamientos
    build: ./alojamiento
    restart: always
    depends_on:
      - mysql_database_alojamientos
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_alojamientos:3306/alojamientos?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root1234
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq
    links:
      - eureka-server

  autenticacion:
    image: agvi_autenticacion
    build: ./autenticacion
    restart: always
    depends_on:
      - eureka-server
      - keycloak
      - gateway
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:9090/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:9090/realms/tutorial-api/protocol/openid-connect/certs
      keycloack.admin-url: http://keycloak:9090/admin/realms/tutorial-api
    links:
      - eureka-server

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    restart: always
    ports:
      - "9090:9090"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data/
    command: [ "start-dev", "--http-port=9090" ]

  config:
    image: agvi_config
    build: ./config
    restart: always
    depends_on:
      - eureka-server
      - personas
      - alojamientos
      - destinos
      - vueloreserva