server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service
          uri: lb://persona-service
          predicates:
            - Path=/api/persona/**
        - id: destino-service
          uri: lb://destino-service
          predicates:
            - Path=/api/destino/**
        - id: vuelo-reserva-service
          uri: lb://vuelo-reserva-service
          predicates:
            - Path=/api/vuelo/**
        - id: vuelo-reserva-service
          uri: lb://vuelo-reserva-service
          predicates:
            - Path=/api/reserva/**
        - id: alojamientos-service
          uri: lb://alojamientos-service
          predicates:
            - Path=/api/alojamiento/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/tutorial-api
          jwk-set-uri: http://localhost:9090/realms/tutorial-api/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username

logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/