server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-service
          uri: lb://persona-service
          predicates:
            - Path=/api/persona/**
        - id: destino-service
          uri: lb://destino-service
          predicates:
            - Path=/api/destino/**
        - id: vuelo-reserva-service
          uri: lb://vuelo-reserva-service
          predicates:
            - Path=/api/vuelo/**
        - id: vuelo-reserva-service
          uri: lb://vuelo-reserva-service
          predicates:
            - Path=/api/reserva/**
        - id: alojamientos-service
          uri: lb://alojamientos-service
          predicates:
            - Path=/api/alojamiento/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/